---
k3s_context_name: k3s-ansible
k3s_server_location: "/var/lib/rancher/k3s"
k3s_server_role_name: server
k3s_agent_role_name: agent

kubelet_config_enabled: true
kubelet_config_shutdown_grace_period: "30s"
kubelet_config_shutdown_grace_period_critical_pods: "10s"

systemd_dir: "/etc/systemd/system"
api_port: 6443

k3s_gpu_nvidia_enabled: false
k3s_server_longhorn_enabled: true
k3s_agent_longhorn_enabled: true

enable_service_monitors: false

drain_nodes: false
