---

# This file is used to configure the kube-vip manifest files.  It typically does
# not need to be changed but you can at your discretion to suit your environment.
# These variables are used only when HA is enabled and the method chosen is kube-vip.
# More options can be found in ../templates//kube-vip-arp-ds.yaml.j2

# These are commonly changed values for kube-vip.
kube_vip_version: 'v0.4.0'
kube_vip_interface: "{{ ansible_default_ipv4.interface }}"

# These are less commonly changed values for kube-vip.
kube_vip_cidr: '32'
kube_vip_leaseduration: '5'
kube_vip_renewdeadline: '3'
kube_vip_retryperiod: '1'

kube_vip_namespace: 'kube-system'
kube_vip_daemonset_name: 'kube-vip-ds'
kube_vip_container_name: 'kube-vip'
kube_vip_serviceaccount_name: 'kube-vip'
kube_vip_clusterrole_name: 'kube-vip-role'
kube_vip_clusterrolebinding_name: 'kube-vip-binding'

