---
- name: Enable cgroup via boot commandline if not already enabled
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    backrefs: true
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  notify: Reboot Pi
