---
ansible_user: root
server_init_args: >-
  {% if groups['k3s_server'] | length > 1 %}
    {% if ansible_host == hostvars[groups['k3s_server'][0]]['ansible_host'] | default(groups['k3s_server'][0]) %}
      --cluster-init
    {% else %}
      --server https://{{ hostvars[groups['k3s_server'][0]]['ansible_host'] | default(groups['k3s_server'][0]) }}:6443
    {% endif %}
    --token {{ k3s_token }}
  {% endif %}
  {{ extra_server_args | default('') }}
