---
base_packages:
  - curl
  - daemontools
  - net-tools
  - ntp
  - open-iscsi
  - openssh-client
  - vim
etc_hosts_file: /etc/hosts
extra_volumes: {}
os_upgrade: false
required_directories: []
wipe_data: false
