# code: language=ansible
---
- name: Add ArgoCD namespace
  kubernetes.core.k8s:
    state: present
    name: "{{ argocd_namespace }}"
    kind: Namespace

- name: Add docker secret
  kubernetes.core.k8s:
    state: present
    namespace: "pro"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: docker-{{ docker_repo.name }}-creds
        namespace: "{{ argocd_namespace }}"
      data:
        .dockerconfigjson: "{{ docker_repo.dockerconfigjson }}"
      type: kubernetes.io/dockerconfigjson
  loop: "{{ docker_repo_configs }}"
  loop_control:
    loop_var: docker_repo

- name: Add ArgoCD helm repo
  kubernetes.core.helm_repository:
    name: "{{ argocd_helm_repo_name }}"
    repo_url: "{{ argocd_helm_repo_chart }}"

- name: Add ArgoCD vault configuration
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    template:
      - path: vault-configuration.j2

- name: Add plugins
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    src: "{{ role_path }}/files/{{ plugin }}.yaml"
  loop:
    - cmp-avp-plugin
  loop_control:
    loop_var: plugin

- name: Add ApplicationSet SCM Provider secret
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: argocd-github-password
        namespace: "{{ argocd_namespace }}"
      data:
        password: "{{ argocd.github.password | b64encode }}"

- name: Setup repository credential templates
  ansible.builtin.include_tasks:
    file: setup_repository_credential_templates.yml

- name: Add extra rbac rules for argocd
  kubernetes.core.k8s:
    state: present
    template:
      - path: argocd_extra_rbac.j2

- name: Install ArgoCD helm chart
  kubernetes.core.helm:
    update_repo_cache: true
    name: argocd
    kubeconfig: "~/.kube/config.pro.new"
    release_namespace: "{{ argocd_namespace }}"
    create_namespace: true
    chart_ref: "{{ argocd_helm_chart }}"
    chart_version: "{{ argocd_helm_chart_version }}"
    values: "{{ lookup('template', 'argocd_values.yaml') | from_yaml }}"

- name: Wait for ArgoCD to become ready
  kubernetes.core.k8s_info:
    name: "{{ argocd_alias }}-server"
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ argocd_namespace }}"
    wait: true
    wait_sleep: 5
    wait_timeout: 300

- name: Add ArgoCD AppProject for different environments
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    template:
      - path: argocd_app_project.j2
  loop: "{{ argocd.app_projects }}"
  loop_control:
    loop_var: argocd_app_project

- name: Set ArgoCD ApplicationSet fact on organisation
  set_fact:
    k8s_application_set_yaml: '{{ lookup("template", "argocd_application_set.j2") }}'
  loop: "{{ argocd.application_sources }}"
  loop_control:
    loop_var: application_source

- name: echo template
  ansible.builtin.debug:
    msg: "{{ k8s_application_set_yaml }}"
    
- name: Add ArgoCD ApplicationSet on organisation
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    template:
      - path: argocd_application_set.j2
  loop: "{{ argocd.application_sources }}"
  loop_control:
    loop_var: application_source

- name: Add ArgoCD ApplicationSet for provisioning different environments
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    template:
      - path: argocd_application_set_provisioning.j2
  loop: "{{ argocd.application_sets.provisioning }}"
  loop_control:
    loop_var: application_set

- name: Add ArgoCD ApplicationSet for deploying applications from templates
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    template:
      - path: argocd_application_set_applications.j2
  loop: "{{ argocd.application_sets.applications }}"
  loop_control:
    loop_var: application_set
