apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-09-26T09:36:07Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: stregsystemet
  namespace: default
  resourceVersion: "809655"
  uid: 1f5485f0-a839-472e-9cc6-278c9cdf785c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.51.123
  clusterIPs:
  - 10.43.51.123
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32421
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: stregsystemet
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.0.0.100
      ipMode: VIP
    - ip: 10.0.0.101
      ipMode: VIP
    - ip: 10.0.0.102
      ipMode: VIP
    - ip: 10.0.0.103
      ipMode: VIP
    - ip: 10.0.0.104
      ipMode: VIP
    - ip: 10.0.0.105
      ipMode: VIP
    - ip: 10.0.0.200
      ipMode: VIP
