---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: k3s_cluster/prereq
    - role: k3s_cluster/airgap
    - role: k3s_cluster/raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s_cluster/k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - role: k3s_cluster/k3s_agent
