name: Update Versions

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  HELM_CHART_VERSION_FILE: roles/bootstrap/defaults/_version.yaml

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: |
          echo "current_date=$(date --iso-8601=date)" >> $GITHUB_OUTPUT
          echo "helm_chart_version_file=$HELM_CHART_VERSION_FILE" >> $GITHUB_OUTPUT

      - name: Update versions
        id: check
        uses: datahub-local/container-helm-version-updater@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          versions-file: values/_version.yaml
          version-type: minor

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: bump version of Helm Charts until ${{ steps.vars.outputs.current_date }}'
          branch: "chore/bump_help_chart_"
          title: 'Bump versions of Helm Charts (${{ steps.vars.outputs.current_date }})'
